name: Genesis Plus GX Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # image: ["Wii", "GameCube"]
        image: ["Wii"] # only for Wii
    container: devkitpro/devkitppc:latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Wii
      if: ${{ matrix.image == 'Wii' }}
      run: |
        make -f Makefile.wii -j1
    
    - name: Copy Wii artifacts
      if: ${{ matrix.image == 'Wii' }}
      run: | 
        mkdir -p dist/apps/genplus-gx
        mkdir -p dist/genplus-gx/roms
        mkdir dist/genplus-gx/cheats
        mkdir dist/genplus-gx/saves
        touch dist/genplus-gx/roms/romsdir
        touch dist/genplus-gx/cheats/cheatsdir
        touch dist/genplus-gx/saves/savesdir
        cp hbc/* dist/apps/genplus-gx/
        cp genplus_wii.elf genplus_wii.dol dist/apps/genplus-gx/

    - name: Upload Wii artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'Wii' }}
      with: 
        name: Genesis-Plus-GX
        path: |
          dist/apps/genplus-gx/*.dol
          dist/apps/genplus-gx/*.elf  # 确保包含ELF
    
    - name: Build GameCube
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        make -f Makefile.gc -j1
        
    - name: Copy GameCube artifact
      if: ${{ matrix.image == 'GameCube' }}
      run: |
        cp genplus_cube.dol dist/
    
    - name: Upload GameCube artifact
      uses: actions/upload-artifact@v4
      if: ${{ matrix.image == 'GameCube' }}
      with: 
        name: Genesis-Plus-GX-GameCube
        path: |
         dist/
